### PR TITLE
Update queues.md

### PR DESCRIPTION
**Pull request by JonoB**
Add documentation on how to configure queues other than database.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks, but this isn't correct. You should not be putting environment specific things in the config files. Instead, use the .env file.

**Comment by JonoB** [comment]
Can you explain how the default Lumen [queue config file](https://github.com/laravel/lumen-framework/blob/5.2/config/queue.php) accepts .env vars?

**Comment by GrahamCampbell** [comment]
Looks like we need to update it so that it does. ;)

**Comment by JonoB** [comment]
Either that, or just use my method above :)

By default, Lumen uses the `config/queue.php` file if it exists. I wonder what @taylorotwell 's thoughts were/are on this?

**Pull request merged**
